version: "3"

services:
  webapp:
    container_name: mercago-app
    restart: always
    build: .
    ports: 
      - "6000:3000"
    links:
      - database 

  database:
    container_name: mercago-db
    image: mongo
    ports:
      - "27020:27017"